#tSQLt CI

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- CITesting

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: DownloadPackage@0
  displayName: 'Download Package'
  inputs:
    feed: '6859c2dc-e26c-4f93-9db2-74832242fff8'
    definition: '844a5d94-f64b-400a-851b-b0c0d1ad900c'
    version: 0.92.0

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
