# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

schedules:
- cron: "0 6 * * *"
  displayName: Daily 3AM cleanup
  branches:
    include:
    - CITesting
  always: true

variables:
  GetResourceGroupsStatement: 'Get-AzResourceGroup -Tag @{Department="tSQLtCI"; Ephemeral="True"}'

steps:

- task: AzurePowerShell@5
  name: List_RGs_To_Be_Deleted
  inputs:
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    azurePowerShellVersion: 'LatestVersion'
    ScriptType: 'InlineScript'
    Inline: |
      Get-AzResourceGroup -Tag @{Department="tSQLtCI"; Ephemeral="True"} | ForEach-Object { 
        Write-Host $_.ResourceGroupName 
        Get-AzResource -ResourceGroup $_.ResourceGroupName |ForEach{Get-AzResourceLock -ResourceType $_.ResourceType -ResourceName $_.Name -ResourceGroupName $_.ResourceGroupName}
      }
- task: AzurePowerShell@5
  name: Delete_RGs
  inputs:
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    azurePowerShellVersion: 'LatestVersion'
    ScriptType: 'InlineScript'
    Inline: |
      Get-AzResourceGroup -Tag @{Department="tSQLtCI"; Ephemeral="True"} | ForEach-Object { 
          Write-Host "Deleting ResourceGroup:" $_.ResourceGroupName 
          Write-Host "Removing Locks"
          Get-AzResource -ResourceGroup $_.ResourceGroupName |ForEach{
            Get-AzResourceLock -ResourceType $_.ResourceType -ResourceName $_.Name -ResourceGroupName $_.ResourceGroupName|ForEach{
              Write-Host $_.ResourceType "->" $_.ResourceName
              $_ | Remove-AzResourceLock -Force 
            }
          }
          Write-Host "Removing RG";
          $_ | Remove-AzResourceGroup -Force 
          Write-Host "Done" 
      }
      #Start-Job -InputObject $_ -ScriptBlock { } 
      #Get-AzResourceGroup -Tag @{Department="tSQLtCI"; Ephemeral="True"} | ForEach-Object { $_ | Remove-AzResourceGroup -Force } 
