# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Date:yyyyMMdd)$(Rev:.r)($(Build.BuildId))

trigger:
- CITesting

pool:
  vmImage: 'vs2017-win2016'

variables:
  NamePreFix: 'tSQLtCI_DevTestLab_'


steps:

- task: CmdLine@2
  condition: false
  inputs:
    script: |
      echo end pipeline here      
      echx

- task: PowerShell@2
  name: Generate_DevTest_Lab_Name
  inputs:
    targetType: 'inline'
    script: |
      $DevTestLabName = If ([string]::IsNullOrEmpty($env:DevTestLabNameOverride)) {("$(NamePreFix)" + (Get-Date).tostring(“yyyyMMdd”) + '_' + $(Build.BuildId))} else {($env:DevTestLabNameOverride)}
      $DevTestLabRGName = $DevTestLabName+'_RG'
      $DevTestLabVNetName = $DevTestLabName+'_VNet0001'
      $vmName = If ([string]::IsNullOrEmpty($env:vmNameOverride)) {('$(Build.BuildId)'+(('$(template)').replace('-',''))+''+$DevTestLabName).substring(0,15)} else {($env:vmNameOverride)}
      Write-Host 'DevTestLabRGName: ' $DevTestLabRGName
      Write-Host "##vso[task.setvariable variable=DevTestLabRGName;]$DevTestLabRGName"
      Write-Host 'DevTestLabName: ' $DevTestLabName
      Write-Host "##vso[task.setvariable variable=DevTestLabName;]$DevTestLabName"
      Write-Host 'DevTestLabVNetName: ' $DevTestLabVNetName
      Write-Host "##vso[task.setvariable variable=DevTestLabVNetName;]$DevTestLabVNetName"
      Write-Host 'vmName: ' $vmName
      Write-Host "##vso[task.setvariable variable=vmName;]$vmName"


- task: AzurePowerShell@4
  name: Create_Resource_Group
  condition: and(succeeded(), eq(variables['CreateNewEnvironment'], '1'))
  inputs:
    azurePowerShellVersion: 'LatestVersion'
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    ScriptType: 'InlineScript'
    Inline: |
      Write-Host 'Creating Resource Group:' $(DevTestLabRGName)
      New-AzResourceGroup -Name "$(DevTestLabRGName)" -Location "East US 2" -Tag @{Department="tSQLtCI"; Ephemeral="True"} -Force
      Write-Host 'Done.'

- task: AzureResourceManagerTemplateDeployment@3
  name: Validate_VNet_ArmTemplate
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    subscriptionId: '58c04a99-5b92-410c-9e41-10262f68ca80'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(DevTestLabRGName)'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'CI/CreateVNetTemplate.json'
    deploymentMode: 'Validation'

- task: AzureResourceManagerTemplateDeployment@3
  name: Validate_DTL_ArmTemplate
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    subscriptionId: '58c04a99-5b92-410c-9e41-10262f68ca80'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(DevTestLabRGName)'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'CI/DevTestLabTemplate.json'
    deploymentMode: 'Validation'

- task: AzureResourceManagerTemplateDeployment@3
  name: Validate_VM_ArmTemplate
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    subscriptionId: '58c04a99-5b92-410c-9e41-10262f68ca80'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(DevTestLabRGName)'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'CI/CreateVMTemplate.json'
    deploymentMode: 'Validation'


- task: AzurePowerShell@4
  name: Create_VNet
  condition: and(succeeded(), eq(variables['CreateNewEnvironment'], '1'))
  inputs:
    azurePowerShellVersion: 'LatestVersion'
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    ScriptType: 'InlineScript'
    Inline: |
      Set-Location $(Build.Repository.LocalPath)
      $VNet = New-AzResourceGroupDeployment -ResourceGroupName "$(DevTestLabRGName)" -TemplateFile "CI/CreateVNetTemplate.json" -VNet_name "$(DevTestLabVNetName)"
      $DevTestLabVNetSubnetName = $VNet.Outputs.subnetName.Value
      Write-Host 'DevTestLabVNetSubnetName: ' $DevTestLabVNetSubnetName
      Write-Host "##vso[task.setvariable variable=DevTestLabVNetSubnetName;]$DevTestLabVNetSubnetName"

- task: AzurePowerShell@4
  name: GetSubnetName
  inputs:
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    azurePowerShellVersion: 'LatestVersion'
    ScriptType: 'InlineScript'
    Inline: |
      Set-Location $(Build.Repository.LocalPath)
      Write-Host "Getting DevTestLabVNetSubnetName"
      $DevTestLabVNetSubnetName = (Get-AzResource -ResourceGroupName "$(DevTestLabRGName)" -ResourceType "Microsoft.Network/virtualNetworks" -Name "$(DevTestLabVNetName)").Properties.Subnets[0].Name
      Write-Host 'DevTestLabVNetSubnetName: ' $DevTestLabVNetSubnetName
      Write-Host "##vso[task.setvariable variable=DevTestLabVNetSubnetName;]$DevTestLabVNetSubnetName"


- task: AzurePowerShell@4
  name: Create_DevTest_Lab_With_Other_Resources
  condition: and(succeeded(), eq(variables['CreateNewEnvironment'], '1'))
  inputs:
    azurePowerShellVersion: 'LatestVersion'
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    ScriptType: 'InlineScript'
    Inline: |
      Set-Location $(Build.Repository.LocalPath)
      New-AzResourceGroupDeployment -ResourceGroupName "$(DevTestLabRGName)" -TemplateFile "CI/DevTestLabTemplate.json" -newLabName "$(DevTestLabName)" -VNetName "$(DevTestLabVNetName)" -SubNetName "$(DevTestLabVNetSubnetName)"


- task: AzurePowerShell@4
  name: Get_DevTest_Lab_Environment_Variables
  inputs:
    azurePowerShellVersion: 'LatestVersion'
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    ScriptType: 'InlineScript'
    Inline: |
      Write-Host 'GetAzResource'
      Get-AzResource -ResourceGroupName "$(DevTestLabRGName)" -ResourceType "Microsoft.Storage/storageAccounts"
      Get-AzResource -ResourceGroupName "$(DevTestLabRGName)" -ResourceType "Microsoft.Network/virtualNetworks"
      Write-Host '-------------'
      $DevTestLabStorageAccount = (Get-AzResource -ResourceGroupName "$(DevTestLabRGName)" -ResourceType "Microsoft.Storage/storageAccounts").ResourceName
      Write-Host "DevTestLabStorageAccount: >>>" $DevTestLabStorageAccount "<<<"
      Write-Host "##vso[task.setvariable variable=DevTestLabStorageAccount;]$DevTestLabStorageAccount"
      Write-Host '-------------'
      #$TempDevTestLabVirtualNetwork = @(Get-AzResource -ResourceGroupName "$(DevTestLabRGName)" -ResourceType "Microsoft.Network/virtualNetworks")[0]
      #$DevTestLabVirtualNetworkName = $TempDevTestLabVirtualNetwork.Name
      #Write-Host "DevTestLabVirtualNetworkName: >>>" $DevTestLabVirtualNetworkName "<<<"
      #Write-Host "##vso[task.setvariable variable=DevTestLabVirtualNetworkName;]$DevTestLabVirtualNetworkName"
      #Write-Host '-------------'
      #$DevTestLabVirtualNetworkSubNetName = @(Get-AzVirtualNetwork -Name $TempDevTestLabVirtualNetwork.Name -ResourceGroupName "$(DevTestLabRGName)")[0].SubNets[0].Name
      #Write-Host "DevTestLabVirtualNetworkSubNetName: >>>" $DevTestLabVirtualNetworkSubNetName "<<<"
      #Write-Host "##vso[task.setvariable variable=DevTestLabVirtualNetworkSubNetName;]$DevTestLabVirtualNetworkSubNetName"
      #Write-Host '-------------'
      Write-Host 'Currently Existing tSQLtCI Resource Groups:'
      Get-AzResourceGroup -Tag @{Department="tSQLtCI"; Ephemeral="True"} 



- task: ArchiveFiles@2
  name: Build_DSC_Zip_File_deleteme
  condition: and(succeeded(), eq(variables['CreateNewVM'], '1'))
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/CI/DSC'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/DSC.zip'
    replaceExistingArchive: true
    verbose: true

- task: AzureFileCopy@3
  name: COPY_DSC_zip_to_Azure_Storage_deleteme
  condition: and(succeeded(), eq(variables['CreateNewVM'], '1'))
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/DSC.zip'
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    Destination: 'AzureBlob'
    storage: '$(DevTestLabStorageAccount)'
    ContainerName: 'dsc'
    outputStorageUri: 'DSC_Storage_URI'
    outputStorageContainerSasToken: 'DSC_Storage_SAS_Token'
    sasTokenTimeOutInMinutes: '60'




- task: AzurePowerShell@4
  name: CreateVM
  condition: and(succeeded(), eq(variables['CreateNewVM'], '1'))
  inputs:
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    azurePowerShellVersion: 'LatestVersion'
    ScriptType: 'InlineScript'
    Inline: |
      Set-Location $(Build.Repository.LocalPath)
      Write-Host 'Creating New VM'
      $VM = New-AzResourceGroupDeployment -ResourceGroupName "$(DevTestLabRGName)" -TemplateFile "CI/CreateVMTemplate.json" -labName "$(DevTestLabName)" -newVMName "$(vmName)" -userName "$(userName)" -DevTestLabVirtualNetworkName "$(DevTestLabVNetName)" -DevTestLabVirtualNetworkSubNetName "$(DevTestLabVNetSubnetName)" -password "qTv3f9gduUFuc8BQTZUq4MEcFbY3(2H)" -DSCURI "$(DSC_Storage_URI)" -DSCSAS "$(DSC_Storage_SAS_Token)" -ContactEmail "$(ContactEmail)"
      Write-Host 'Finished Creating New VM'
      $labVMId = $VM.Outputs.labVMId.Value
      Write-Host 'labVMId: ' $labVMId
      Write-Host "##vso[task.setvariable variable=labVMId;]$labVMId"


- task: AzurePowerShell@4
  name: GetLabVmId
  inputs:
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    azurePowerShellVersion: 'LatestVersion'
    ScriptType: 'InlineScript'
    Inline: |
      Set-Location $(Build.Repository.LocalPath)
      Write-Host "Getting labVMId"
      $labVmId = (Get-AzResource -ResourceGroupName "$(DevTestLabRGName)" -ResourceType "Microsoft.DevTestLab/labs/virtualMachines" -Name "$(vmName)").ResourceId
      Write-Host 'labVMId: ' $labVMId
      Write-Host "##vso[task.setvariable variable=labVMId;]$labVMId"



- task: Bash@3
  name: print_environment_variables
  inputs:
    targetType: 'inline'
    script: |
      echo 'env start------------'
      env | sort
      echo 'env stop-------------'


- task: AzurePowerShell@4
  name: get_VM_parameters
  inputs:
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    ScriptType: 'FilePath'
    ScriptPath: 'CI/GetLabVMParams.ps1'
    ScriptArguments: '-labVmId ''$(labVMId)'' ' 
    azurePowerShellVersion: 'LatestVersion'



- task: CmdLine@2
  condition: false
  inputs:
    script: |
      echo end pipeline here      
      echx


- task: ArchiveFiles@2
  name: Build_DSC_Zip_File
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/CI/DSC'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/DSC.zip'
    replaceExistingArchive: true
    verbose: true

- task: AzureFileCopy@3
  name: COPY_DSC_zip_to_Azure_Storage
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/DSC.zip'
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    Destination: 'AzureBlob'
    storage: '$(DevTestLabStorageAccount)'
    ContainerName: 'dsc'
    outputStorageUri: 'DSC_Storage_URI'
    outputStorageContainerSasToken: 'DSC_Storage_SAS_Token'
    sasTokenTimeOutInMinutes: '60'


- task: AzurePowerShell@4
  name: CreateVMDSC
  inputs:
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    azurePowerShellVersion: 'LatestVersion'
    ScriptType: 'InlineScript'
    Inline: |
      Set-Location $(Build.Repository.LocalPath)
      Write-Host 'Creating New DSC'
      $VM = New-AzResourceGroupDeployment -ResourceGroupName "$(DevTestLabRGName)" -TemplateFile "CI/DSCTemplate.json" -labName "$(DevTestLabName)" -newVMName "$(vmName) -DeploymentDebugLogLevel All" 
      Write-Host 'Finished Creating New DSC'




- task: CmdLine@2
  condition: true
  inputs:
    script: |
      echo end pipeline here      
      echx



#- task: CmdLine@2
#  name: Stop_The_PipeLine
#  condition: true
#  inputs:
#    script: |
#      echo end pipeline here
#      
#      echx


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "labVmRgName   $env:labVmRgName ---- labVmName   $env:labVmName"

- task: AzureCLI@2
  name: Get_Vm_Status
  inputs:
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az vm show -g $env:labVmRgName -n NonExistingVM -d'
#    inlineScript: 'az vm show -g $env:labVmRgName -n $env:labVmName -d'



### New-NetFirewallRule -DisplayName "Allow WinRM" -Direction Inbound -LocalPort 5986 -Protocol TCP -Action Allow
### New-NetFirewallRule -DisplayName "Allow SQLServer" -Direction Inbound -LocalPort 1433 -Protocol TCP -Action Allow
### SqlCmd -S localhost -E -Q "PRINT @@VERSION;"
### SqlCmd -S localhost -E -Q "CREATE LOGIN tSQLtExternal WITH PASSWORD = 'qTv3f9gduUFuc8BQTZUq4MEcFbY3(2H)',CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF,DEFAULT_DATABASE = tempdb;ALTER SERVER ROLE sysadmin ADD MEMBER tSQLtExternal;"
### SqlCmd -S localhost -E -Q "EXEC xp_instance_regwrite N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'LoginMode', REG_DWORD, 2"
### Restart-Service -Name "SQL Server (MSSQLSERVER)"
### sql2014sp3d.eastus2.cloudapp.azure.com

- task: PowerShellOnTargetMachines@3
  inputs:
    Machines: '$(labVMFqdn)'
    UserName: 'tSQLt'
    UserPassword: 'qTv3f9gduUFuc8BQTZUq4MEcFbY3(2H)'
    InlineScript: |
      # Write your powershell commands here.
      
      Write-Output "Hello World"