# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- CITesting

pool:
  vmImage: 'vs2017-win2016'

steps:

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'tSQLt CI Subscription(58c04a99-5b92-410c-9e41-10262f68ca80)'
    KeyVaultName: 'tSQLtCI1078'
    SecretsFilter: '*'

- task: AzureDevTestLabsCreateVM@3
  inputs:
    azureSubscription: 'tSQLt CI Subscription(1)(58c04a99-5b92-410c-9e41-10262f68ca80)'
    LabID: /subscriptions/58c04a99-5b92-410c-9e41-10262f68ca80/resourceGroups/tSQLtCI_DevTestLab_3_RG/providers/Microsoft.DevTestLab/labs/tSQLtCI_DevTestLab_3
    VirtualMachineName: 'SQL2008SP3'
    TemplateFile: 'CI/CreateVMTemplate.json'